# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_created=True)),
                ('owner', models.CharField(blank=True, max_length=20)),
                ('make', models.CharField(blank=True, max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('light1isON', models.BooleanField(default=False)),
                ('light2isON', models.BooleanField(default=False)),
                ('light3isON', models.BooleanField(default=False)),
                ('stove1State', models.IntegerField(default=0)),
                ('fan1State', models.IntegerField(default=0)),
                ('geyser1State', models.IntegerField(default=0)),
                ('homeTemp', models.FloatField(default=0)),
            ],
        ),
    ]
