# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='last_updated',
            new_name='date_modified',
        ),
        migrations.AlterField(
            model_name='device',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
