# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171228_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='owner',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
